services:
  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'

  server1: &server-template
    image: kptunnel
    build: ./kptunnel-docker
    command: '/kptunnel r-wsserver :6666 :88,test:80'
    ports:
      - '8001:88'

  server2:
    <<: *server-template
    ports:
      - '8002:88'

  server3:
    <<: *server-template
    ports:
      - '8003:88'
